In [12]:
caffe_root ="/home/lqp/py-faster-rcnn/caffe-fast-rcnn/"
import sys
sys.path.insert(0,caffe_root+"python")
import caffe
import numpy as np
import yaml
from generate_anchors import generate_anchors

In [13]:
height=50;
width=50;
_feat_stride=16 
#feat_stride表示最后一个feature map的尺度和原始图像的比例，
#比如原来是800*800最后一个feature map是50*50，那feat_stride是800/50=16

In [14]:
shift_x = np.arange(0, width) * _feat_stride
shift_y = np.arange(0, height) * _feat_stride
shift_x, shift_y = np.meshgrid(shift_x, shift_y)
shifts = np.vstack((shift_x.ravel(), shift_y.ravel(),
                    shift_x.ravel(), shift_y.ravel())).transpose()#生成所有anchors

In [15]:
np.arange(0, width) * _feat_stride

array([  0,  16,  32,  48,  64,  80,  96, 112, 128, 144, 160, 176, 192,
       208, 224, 240, 256, 272, 288, 304, 320, 336, 352, 368, 384, 400,
       416, 432, 448, 464, 480, 496, 512, 528, 544, 560, 576, 592, 608,
       624, 640, 656, 672, 688, 704, 720, 736, 752, 768, 784])

In [16]:
shift_x

array([[  0,  16,  32, ..., 752, 768, 784],
       [  0,  16,  32, ..., 752, 768, 784],
       [  0,  16,  32, ..., 752, 768, 784],
       ..., 
       [  0,  16,  32, ..., 752, 768, 784],
       [  0,  16,  32, ..., 752, 768, 784],
       [  0,  16,  32, ..., 752, 768, 784]])

In [17]:
shift_y

array([[  0,   0,   0, ...,   0,   0,   0],
       [ 16,  16,  16, ...,  16,  16,  16],
       [ 32,  32,  32, ...,  32,  32,  32],
       ..., 
       [752, 752, 752, ..., 752, 752, 752],
       [768, 768, 768, ..., 768, 768, 768],
       [784, 784, 784, ..., 784, 784, 784]])

In [18]:
shifts

array([[  0,   0,   0,   0],
       [ 16,   0,  16,   0],
       [ 32,   0,  32,   0],
       ..., 
       [752, 784, 752, 784],
       [768, 784, 768, 784],
       [784, 784, 784, 784]])

In [19]:
shifts.shape

(2500, 4)

In [20]:
_anchors = generate_anchors()
_anchors

array([[ -84.,  -40.,   99.,   55.],
       [-176.,  -88.,  191.,  103.],
       [-360., -184.,  375.,  199.],
       [ -56.,  -56.,   71.,   71.],
       [-120., -120.,  135.,  135.],
       [-248., -248.,  263.,  263.],
       [ -36.,  -80.,   51.,   95.],
       [ -80., -168.,   95.,  183.],
       [-168., -344.,  183.,  359.]])

In [21]:
A = _num_anchors = 9
K = shifts.shape[0]

In [22]:
anchors = _anchors.reshape((1, A, 4)) + \
                  shifts.reshape((1, K, 4)).transpose((1, 0, 2))
anchors = anchors.reshape((K * A, 4))

In [25]:
anchors.shape

(22500, 4)

In [26]:
anchors

array([[  -84.,   -40.,    99.,    55.],
       [ -176.,   -88.,   191.,   103.],
       [ -360.,  -184.,   375.,   199.],
       ..., 
       [  748.,   704.,   835.,   879.],
       [  704.,   616.,   879.,   967.],
       [  616.,   440.,   967.,  1143.]])

In [43]:
for i in range(len(anchors)):
    print("("+str((anchors[i][3]+anchors[i][1])/2)+"\t,"+str((anchors[i][2]+anchors[i][0])/2)+")\t" + 
         "h:  "+ str(anchors[i][3]-anchors[i][1]+1)+
         "\tw:  "+ str(anchors[i][2]-anchors[i][0]+1)+
         "\th/w: "+str((anchors[i][3]-anchors[i][1]+1)/(anchors[i][2]-anchors[i][0]+1)))

(7.5	,7.5)	h:  96.0	w:  184.0	h/w: 0.521739130435
(7.5	,7.5)	h:  192.0	w:  368.0	h/w: 0.521739130435
(7.5	,7.5)	h:  384.0	w:  736.0	h/w: 0.521739130435
(7.5	,7.5)	h:  128.0	w:  128.0	h/w: 1.0
(7.5	,7.5)	h:  256.0	w:  256.0	h/w: 1.0
(7.5	,7.5)	h:  512.0	w:  512.0	h/w: 1.0
(7.5	,7.5)	h:  176.0	w:  88.0	h/w: 2.0
(7.5	,7.5)	h:  352.0	w:  176.0	h/w: 2.0
(7.5	,7.5)	h:  704.0	w:  352.0	h/w: 2.0
(7.5	,23.5)	h:  96.0	w:  184.0	h/w: 0.521739130435
(7.5	,23.5)	h:  192.0	w:  368.0	h/w: 0.521739130435
(7.5	,23.5)	h:  384.0	w:  736.0	h/w: 0.521739130435
(7.5	,23.5)	h:  128.0	w:  128.0	h/w: 1.0
(7.5	,23.5)	h:  256.0	w:  256.0	h/w: 1.0
(7.5	,23.5)	h:  512.0	w:  512.0	h/w: 1.0
(7.5	,23.5)	h:  176.0	w:  88.0	h/w: 2.0
(7.5	,23.5)	h:  352.0	w:  176.0	h/w: 2.0
(7.5	,23.5)	h:  704.0	w:  352.0	h/w: 2.0
(7.5	,39.5)	h:  96.0	w:  184.0	h/w: 0.521739130435
(7.5	,39.5)	h:  192.0	w:  368.0	h/w: 0.521739130435
(7.5	,39.5)	h:  384.0	w:  736.0	h/w: 0.521739130435
(7.5	,39.5)	h:  128.0	w:  128.0	h/w: 1.0
(7.5	,39.5)	h